# Goal
std_msgs/Header header
geometry_msgs/Pose start
geometry_msgs/Pose goal

uint32 max_iterations 32768
uint32 max_tree_size 16384

---
# Result
nav_msgs/Path fin_path
bool success false

---
# Feedback
nav_msgs/Path inter_path