# Goal
geometry_msgs/PoseStamped start
geometry_msgs/PoseStamped goal

uint32 max_iterations 128
uint32 max_tree_size 128

---
# Result
nav_msgs/Path path
bool success false

---
# Feedback
uint32 iterations
uint32 tree_start_size
uint32 tree_goal_size
